version: "3.7"
services:
  frontend:
    container_name: frontend
    build: 
      context: frontend
      target: production
    restart: always
    ports:
      - 80:80
    stdin_open: true
    networks:
      - frontend-backend
    depends_on:
      - backend

  backend:
    container_name: backend
    build: 
      context: backend
    restart: always
    depends_on:
      - mongo
    networks:
      - backend-mongo
      - frontend-backend

  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - backend-mongo
networks:
  frontend-backend:
  backend-mongo:
